{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "messageman_consumer_connected_total{name=~\"$name\"}"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "messageman_connection_active_total"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"messageman\"}) OR vector(0)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Events/Jobs Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(messageman_send_duration_seconds_count{name=~\"$name\"}[1m]))",
     "legendFormat": "name: {{ name }} service: {{ service }}"
    }
   ]
  },
  {
   "title": "Events/Jobs Consumed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(messageman_consume_duration_seconds_count{service=~\"$service\", name=~\"$name\"}[1m]))",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(messageman_connection_active_total{name=~\"$name\"}) by (instance)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Send Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (rate(messageman_send_duration_seconds_sum{name=~\"$name\"}[1m])) / sum without (instance)(rate(messageman_send_duration_seconds_count{name=~\"$name\"}[1m]))",
     "legendFormat": "name: {{ name }} service: {{ service }}"
    }
   ]
  },
  {
   "title": "Consume Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (rate(messageman_consume_duration_seconds_sum{service=~\"$service\", name=~\"$name\"}[1m])) / sum without (instance) (rate(messageman_consume_duration_seconds_coun{service=~\"$service\", name=~\"$name\"}[1m]))",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(messageman_consumer_connected_total{service=~\"$service\", name=~\"$name\"}) OR vector(0)",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Send Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(messageman_send_errors_total{service=~\"$service\", name=~\"$name\"}[1m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consume Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(messageman_consume_errors_total{service=~\"$service\", name=~\"$name\"}[1m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (increase(messageman_errors_total{service=~\"$service\", name=~\"$name\"}[1m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}